# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Make Documentation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdoc
        python -m pip install -r requirements.txt
    - name: Build documentation
      run: |
        pdoc -o documentation -d google --logo-link "https://static.thenounproject.com/png/400559-200.png" staresc
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_2_REPO_DOCUMENTATION }}
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_2_REPO_DOCUMENTATION }}
      with:
        source-directory: 'documentation'
        destination-github-username: 'staresc'
        destination-repository-name: 'documentation'
        user-email: casalinovalerio.cv@gmail.com
        target-branch: main
