name: Standalone Executable

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install pyinstaller
    - name: Build
      run: |
        pyinstaller -F staresc.py
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: dist/staresc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
