name: release

on:
  push:
    tags:
      - 'v*.*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix: 
        platform: [ ubuntu-latest , windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install pyinstaller
    - name: Build
      run: |
        pyinstaller -F staresc.py
    - name: Upload Artifacts (Windows)
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: staresc-artifact-${{ matrix.platform }}
        path: dist/staresc.exe

    - name: Upload Artifacts (Linux)
      if: matrix.platform == 'ubuntu-latest'
      uses: actions/upload-artifact@master
      with:
        name: staresc-artifact-${{ matrix.platform }}
        path: dist/staresc

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Artifacts Folder
      run: mkdir -p dist

    - name: Donwload Windows Artifact
      uses: actions/download-artifact@master
      with:
        name: staresc-artifact-windows-latest
        path: dist

    - name: Donwload Linux Artifact
      uses: actions/download-artifact@master
      with:
        name: staresc-artifact-ubuntu-latest
        path: dist

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            dist/staresc
            dist/staresc.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
